# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: TNH
copyright: TNH is a Church of the Redeemer small group

repo_name: acceptilation/tnh.app
repo_url: https://github.com/acceptilation/tnh.app

plugins:
  - privacy
  - git-revision-date-localized:
      type: timeago
  - git-committers:
      repository: acceptilation/tnh.app
      branch: main

extra:
  homepage: https://www.redeemeratlanta.org

  social:
    - name: Church of the Redeemer
      link: https://www.redeemeratlanta.org
      icon: material/cross-bolnisi

    - name: The Gospel Coalition
      link: https://www.thegospelcoalition.org
      icon: simple/square

    - name: BibleProject
      link: https://bibleproject.com
      icon: material/chat

    - name: Zondervan Academic
      link: https://zondervanacademic.com
      icon: simple/zilch

    - name: InterVarsity Press
      link: https://www.ivpress.com
      icon: material/waves

theme:
  name: material
  favicon: favicon.png
  icon:
    logo: material/cross-bolnisi
    repo: simple/github

  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
