# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: TNH

plugins:
  - privacy
extra:
  homepage: https://www.redeemeratlanta.org

theme:
  name: material
  favicon: favicon.png
  icon:
    logo: material/cross-bolnisi

  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
