name: mkdocs-build-deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # for git-revision-date-localized-plugin

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          cache: pip
          python-version: 3.x

      - name: Install Python packages
        run: pip install --requirement requirements.txt;

      - name: Build and deploy MkDocs
        run: mkdocs gh-deploy --force;
