name: zensical-deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  call-external:
    uses: acceptilation/actions/.github/workflows/zensical.yaml@main
